platform :ios, '9.0'
use_frameworks!

target 'mangaReader' do
    pod 'Alamofire', '~> 4.6.0'
    pod 'AlamofireImage', '~> 3.3'
    pod 'AlamofireObjectMapper', '~> 5.0.0'
    pod 'SnapKit', '~> 4.0.0'
    pod 'NVActivityIndicatorView', '~> 4.1.1'
    pod 'RealmSwift', '~> 3.1.1'
    pod 'TagListView', '~> 1.3.0'
    # pod 'BPStatusBarAlert', '~> 0.1.5'
    pod 'Toast-Swift', '~> 3.0.1'
end
