platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'mangaReader' do
    # RX
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    
    # Network
    pod 'Alamofire', '~> 4.6.0'
    pod 'AlamofireImage', '~> 3.3'
    
    # Database
    pod 'RealmSwift', '~> 3.7.4'
    
    # DI
    pod 'Swinject'
    
    # UI
    pod 'SnapKit', '~> 4.0.0'
    pod 'NVActivityIndicatorView', '~> 4.1.1'
    pod 'TagListView', '~> 1.3.0'
    # pod 'BPStatusBarAlert', '~> 0.1.5'
    pod 'Toast-Swift', '~> 3.0.1'
    pod 'SVPullToRefresh'
    
    # ADS
    pod 'VungleSDK-iOS', '~> 6.2.0'
    pod 'Google-Mobile-Ads-SDK', '~> 7.31.0'
    pod 'UnityAds', '~> 2.1.0'
    
    pod 'FacebookCore', '~> 0.3.1'
    pod 'PersonalizedAdConsent'
end
